version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/product/db/query/"
    schema: "../internal/product/db/migration/"
    gen:
      go:
        package: "db"
        out: "../internal/product/db/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
          - db_type: "timestamptz"
            go_type:
              type: "time.Time"
          