version: "3.9"
services:

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:1.14.0
    ports:
      - "8001:8001"
    networks:
      - redis-cluster-network

networks:
  redis-cluster-network:
    driver: bridge
