// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type ProductImage struct {
	ID          uuid.UUID `json:"id"`
	ContentType string    `json:"content_type"`
	ProductID   uuid.UUID `json:"product_id"`
	Alt         string    `json:"alt"`
	CreatedAt   time.Time `json:"created_at"`
}

type ProductVideo struct {
	ID          uuid.UUID `json:"id"`
	ContentType string    `json:"content_type"`
	ProductID   uuid.UUID `json:"product_id"`
	Alt         string    `json:"alt"`
	CreatedAt   time.Time `json:"created_at"`
}
