// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreateProductVideo(ctx context.Context, arg CreateProductVideoParams) (ProductVideo, error)
	DeleteProductImageByID(ctx context.Context, id uuid.UUID) (ProductImage, error)
	DeleteProductImageByProductID(ctx context.Context, productID uuid.UUID) ([]ProductImage, error)
	DeleteProductVideoByID(ctx context.Context, id uuid.UUID) (ProductVideo, error)
	DeleteProductVideoByProductID(ctx context.Context, productID uuid.UUID) ([]ProductVideo, error)
	GetProductImageByID(ctx context.Context, id uuid.UUID) (ProductImage, error)
	GetProductImagesByProductID(ctx context.Context, productID uuid.UUID) ([]ProductImage, error)
	GetProductVideoByID(ctx context.Context, id uuid.UUID) (ProductVideo, error)
	GetProductVideoByProductID(ctx context.Context, productID uuid.UUID) ([]ProductVideo, error)
}

var _ Querier = (*Queries)(nil)
