service:
  Name: order_service
  Mode: Development
  Debug: true
  ReadTimeout: 5
  WriteTimeout: 5

http:
  Port: 8082
  Mode: debug

grpc:
  Port: 50053
  Timeout: 15
  Time: 5
  MaxConnectionIdle: 30
  MaxConnectionAge: 5

grpcClient:
  Product: localhost:50052
  Auth: localhost:50051

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  DNS_URL: postgresql://postgres:postgres@localhost:5432/order_db?sslmode=disable
  Migration: file://internal/order/db/migration

migration:
  Enable: true
  Recreate: false

rpcEndpoints:
  authSvc: ":50051"
  productSvc: ":50052"

kafka:
  Brokers: ["localhost:9091"]

localCache:
  ExpirationTime: 600

redisCache:
  Address: "localhost:7000"
  Password: ""
  DB: 0
  PoolSize: 10
  MaxRetries: 3
  ExpirationTime: 900
  CuckooFilter:
    Capacity: 600000
    BucketSize: 2
    MaxIterations: 20