// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	DeleteOrder(ctx context.Context, id uuid.UUID) ([]Order, error)
	GetOrder(ctx context.Context, id uuid.UUID) ([]Order, error)
}

var _ Querier = (*Queries)(nil)
