service:
  Name: orchestrator_service
  Mode: Development
  Debug: true
  ReadTimeout: 5
  WriteTimeout: 5

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

grpcClient:
  Timeout: 5
  Account: account_service:50051
  Product: product_service:50051
  Order: order_service:50051

kafka:
  Brokers: ["host.docker.internal:9091"]
