service:
  Name: mail_service
  Mode: Development
  Debug: true
  ReadTimeout: 5
  WriteTimeout: 5

http:
  Port: 8080
  Mode: debug

grpc:
  Port: 50051
  Timeout: 15
  Time: 5
  MaxConnectionIdle: 30
  MaxConnectionAge: 5  

kafka:
  Brokers: ["kafka:9091"]

mail:
  MailDomain: host.docker.internal
  MailHostSend: host.docker.internal
  MailPortSend: 1025
  MailUsername: 
  MailPassword: 
  MailEncryption: none
  MailFromName: DoVanTu
  MailFromAddress:
