// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	DeletePayment(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentById(ctx context.Context, id uuid.UUID) (Payment, error)
}

var _ Querier = (*Queries)(nil)
