service:
  Name: media_service
  Mode: Development
  Debug: true
  ReadTimeout: 5
  WriteTimeout: 5

http:
  Port: 8086
  Mode: debug

postgres:
  DNS_URL: postgresql://postgres:postgres@localhost:5432/media_db?sslmode=disable
  Migration: file://internal/media/db/migration

grpc:
  Port: 50055
  Timeout: 15
  Time: 5
  MaxConnectionIdle: 30
  MaxConnectionAge: 5
  ShutdownWait: 0

grpcClient:
  Timeout: 5
  Account: localhost:50051
  Product: localhost:50052
  Order: localhost:50053

minio:
  Endpoint: "localhost:9000"
  Username: admin123456
  Password: secret123456


kafka:
  Brokers: ["localhost:9091"]

