// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	DeleteComment(ctx context.Context, arg DeleteCommentParams) ([]Comment, error)
	DeleteCommentById(ctx context.Context, id uuid.UUID) (Comment, error)
	GetAllComments(ctx context.Context, arg GetAllCommentsParams) ([]Comment, error)
	GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error)
	GetCommentByProductID(ctx context.Context, productID uuid.UUID) ([]Comment, error)
	GetCommentForUpdate(ctx context.Context, id uuid.UUID) (Comment, error)
	GetMaxRightIndex(ctx context.Context, parentID pgtype.UUID) (interface{}, error)
	ListComment(ctx context.Context, arg ListCommentParams) ([]Comment, error)
	UpdateContentComment(ctx context.Context, arg UpdateContentCommentParams) (Comment, error)
	UpdateLeftIndexComment(ctx context.Context, arg UpdateLeftIndexCommentParams) ([]Comment, error)
	UpdateRightIndexComment(ctx context.Context, arg UpdateRightIndexCommentParams) ([]Comment, error)
}

var _ Querier = (*Queries)(nil)
