service:
  Name: comment_service
  Mode: Development
  Debug: true
  ReadTimeout: 5
  WriteTimeout: 5

http:
  Port: 8087
  Mode: debug

grpc:
  Port: 50056
  Timeout: 15
  Time: 5
  MaxConnectionIdle: 30
  MaxConnectionAge: 5
  ShutdownWait: 0

grpcClient:
  Timeout: 5
  Account: "localhost:50051"
  Media: "localhost:50055"

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  DNS_URL: postgresql://postgres:postgres@localhost:5432/comment_db?sslmode=disable
  Migration: file://internal/comment/db/migration

migration:
  Enable: true
  Recreate: false

kafka:
  Brokers: ["localhost:9091"]

localCache:
    ExpirationTime: 600

redisCache:
    Address: ["172.24.83.66:7001", "172.24.83.66:7002", "172.24.83.66:7003","172.24.83.66:7004", "172.24.83.66:7000", "172.24.83.66:7005" ]
    Password: ""
    DB: 0
    PoolSize: 10
    MaxRetries: 3
    ExpirationTime: 900
    CuckooFilter:
      Capacity: 600000
      BucketSize: 2
      MaxIterations: 20


