/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: service_media.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as service_media_pb from './service_media_pb'; // proto import: "service_media.proto"


export class ServiceMediaClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUploadImage = new grpcWeb.MethodDescriptor(
    '/pb.ServiceMedia/UploadImage',
    grpcWeb.MethodType.UNARY,
    service_media_pb.UploadImageRequest,
    service_media_pb.UploadImageResponse,
    (request: service_media_pb.UploadImageRequest) => {
      return request.serializeBinary();
    },
    service_media_pb.UploadImageResponse.deserializeBinary
  );

  uploadImage(
    request: service_media_pb.UploadImageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<service_media_pb.UploadImageResponse>;

  uploadImage(
    request: service_media_pb.UploadImageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_media_pb.UploadImageResponse) => void): grpcWeb.ClientReadableStream<service_media_pb.UploadImageResponse>;

  uploadImage(
    request: service_media_pb.UploadImageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_media_pb.UploadImageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.ServiceMedia/UploadImage',
        request,
        metadata || {},
        this.methodDescriptorUploadImage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.ServiceMedia/UploadImage',
    request,
    metadata || {},
    this.methodDescriptorUploadImage);
  }

  methodDescriptorDeleteImage = new grpcWeb.MethodDescriptor(
    '/pb.ServiceMedia/DeleteImage',
    grpcWeb.MethodType.UNARY,
    service_media_pb.DeleteImageRequest,
    service_media_pb.DeleteImageResponse,
    (request: service_media_pb.DeleteImageRequest) => {
      return request.serializeBinary();
    },
    service_media_pb.DeleteImageResponse.deserializeBinary
  );

  deleteImage(
    request: service_media_pb.DeleteImageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<service_media_pb.DeleteImageResponse>;

  deleteImage(
    request: service_media_pb.DeleteImageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_media_pb.DeleteImageResponse) => void): grpcWeb.ClientReadableStream<service_media_pb.DeleteImageResponse>;

  deleteImage(
    request: service_media_pb.DeleteImageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_media_pb.DeleteImageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.ServiceMedia/DeleteImage',
        request,
        metadata || {},
        this.methodDescriptorDeleteImage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.ServiceMedia/DeleteImage',
    request,
    metadata || {},
    this.methodDescriptorDeleteImage);
  }

}

